jogador = {
  "count": 20,
  "count_total": 20542,
  "page": 5,
  "page_total": 1028,
  "items_per_page": 20,
  "items": [
    {
      "id": 93971,
      "resource_id": 246529,
      "name": "Bergkamp",
      "age": None,
      "resource_base_id": 246529,
      "fut_bin_id": 28708,
      "fut_wiz_id": 19816,
      "first_name": "Dennis",
      "last_name": "Bergkamp",
      "common_name": "Bergkamp",
      "height": 183,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 34,
      "club": 112658,
      "rarity": 84,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CF",
      "skill_moves": 4,
      "weak_foot": 4,
      "foot": "Right",
      "attack_work_rate": "MED",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 79,
      "pace": 85,
      "shooting": 93,
      "passing": 89,
      "dribbling": 94,
      "defending": 39,
      "physicality": 79,
      "pace_attributes": {
        "acceleration": 86,
        "sprint_speed": 84
      },
      "shooting_attributes": {
        "positioning": 96,
        "finishing": 95,
        "shot_power": 93,
        "long_shots": 86,
        "volleys": 98,
        "penalties": 94
      },
      "passing_attributes": {
        "vision": 96,
        "crossing": 85,
        "free_kick_accuracy": 85,
        "short_passing": 91,
        "long_passing": 81,
        "curve": 87
      },
      "dribbling_attributes": {
        "agility": 88,
        "balance": 83,
        "reactions": 96,
        "ball_control": 99,
        "dribbling": 92,
        "composure": 98
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 73,
        "standing_tackle": 42,
        "sliding_tackle": 37
      },
      "physicality_attributes": {
        "jumping": 79,
        "stamina": 83,
        "strength": 78,
        "aggression": 75
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93972,
      "resource_id": 246503,
      "name": "Madeira Caeiro Figo",
      "age": None,
      "resource_base_id": 246503,
      "fut_bin_id": 28707,
      "fut_wiz_id": 19818,
      "first_name": "Luís Filipe",
      "last_name": "Madeira Caeiro Figo",
      "common_name": "Luís Figo",
      "height": 180,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 38,
      "club": 112658,
      "rarity": 84,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "RM",
      "skill_moves": 4,
      "weak_foot": 4,
      "foot": "Right",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "LOW",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 82,
      "pace": 93,
      "shooting": 90,
      "passing": 92,
      "dribbling": 94,
      "defending": 42,
      "physicality": 82,
      "pace_attributes": {
        "acceleration": 95,
        "sprint_speed": 92
      },
      "shooting_attributes": {
        "positioning": 93,
        "finishing": 91,
        "shot_power": 88,
        "long_shots": 91,
        "volleys": 82,
        "penalties": 86
      },
      "passing_attributes": {
        "vision": 91,
        "crossing": 93,
        "free_kick_accuracy": 96,
        "short_passing": 93,
        "long_passing": 88,
        "curve": 89
      },
      "dribbling_attributes": {
        "agility": 93,
        "balance": 82,
        "reactions": 90,
        "ball_control": 95,
        "dribbling": 97,
        "composure": 86
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 65,
        "standing_tackle": 42,
        "sliding_tackle": 39
      },
      "physicality_attributes": {
        "jumping": 75,
        "stamina": 91,
        "strength": 80,
        "aggression": 78
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93973,
      "resource_id": 246528,
      "name": "Puyol Saforcada",
      "age": None,
      "resource_base_id": 246528,
      "fut_bin_id": 28706,
      "fut_wiz_id": 19819,
      "first_name": "Carles",
      "last_name": "Puyol Saforcada",
      "common_name": "Carles Puyol",
      "height": 178,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 45,
      "club": 112658,
      "rarity": 84,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CB",
      "skill_moves": 2,
      "weak_foot": 3,
      "foot": "Right",
      "attack_work_rate": "MED",
      "defense_work_rate": "HIGH",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 73,
      "pace": 75,
      "shooting": 46,
      "passing": 70,
      "dribbling": 62,
      "defending": 96,
      "physicality": 92,
      "pace_attributes": {
        "acceleration": 74,
        "sprint_speed": 75
      },
      "shooting_attributes": {
        "positioning": 45,
        "finishing": 36,
        "shot_power": 72,
        "long_shots": 43,
        "volleys": 38,
        "penalties": 56
      },
      "passing_attributes": {
        "vision": 60,
        "crossing": 71,
        "free_kick_accuracy": 49,
        "short_passing": 78,
        "long_passing": 75,
        "curve": 52
      },
      "dribbling_attributes": {
        "agility": 56,
        "balance": 57,
        "reactions": 92,
        "ball_control": 67,
        "dribbling": 55,
        "composure": 87
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 94,
        "standing_tackle": 96,
        "sliding_tackle": 95
      },
      "physicality_attributes": {
        "jumping": 88,
        "stamina": 88,
        "strength": 94,
        "aggression": 94
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93974,
      "resource_id": 258862,
      "name": "Beckham",
      "age": None,
      "resource_base_id": 258862,
      "fut_bin_id": 28705,
      "fut_wiz_id": 19821,
      "first_name": "David",
      "last_name": "Beckham",
      "common_name": "Beckham",
      "height": 182,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 14,
      "club": 112658,
      "rarity": 84,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "RM",
      "skill_moves": 3,
      "weak_foot": 3,
      "foot": "Right",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "HIGH",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 86,
      "pace": 84,
      "shooting": 91,
      "passing": 97,
      "dribbling": 90,
      "defending": 70,
      "physicality": 84,
      "pace_attributes": {
        "acceleration": 81,
        "sprint_speed": 86
      },
      "shooting_attributes": {
        "positioning": 93,
        "finishing": 85,
        "shot_power": 97,
        "long_shots": 99,
        "volleys": 85,
        "penalties": 92
      },
      "passing_attributes": {
        "vision": 96,
        "crossing": 99,
        "free_kick_accuracy": 99,
        "short_passing": 94,
        "long_passing": 98,
        "curve": 99
      },
      "dribbling_attributes": {
        "agility": 80,
        "balance": 86,
        "reactions": 96,
        "ball_control": 94,
        "dribbling": 88,
        "composure": 97
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 74,
        "standing_tackle": 70,
        "sliding_tackle": 64
      },
      "physicality_attributes": {
        "jumping": 75,
        "stamina": 95,
        "strength": 79,
        "aggression": 84
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93975,
      "resource_id": 246499,
      "name": "Nesta",
      "age": None,
      "resource_base_id": 246499,
      "fut_bin_id": 28704,
      "fut_wiz_id": 19817,
      "first_name": "Alessandro",
      "last_name": "Nesta",
      "common_name": "Nesta",
      "height": 187,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 27,
      "club": 112658,
      "rarity": 84,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CB",
      "skill_moves": 2,
      "weak_foot": 3,
      "foot": "Right",
      "attack_work_rate": "MED",
      "defense_work_rate": "HIGH",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 73,
      "pace": 74,
      "shooting": 43,
      "passing": 67,
      "dribbling": 70,
      "defending": 96,
      "physicality": 89,
      "pace_attributes": {
        "acceleration": 75,
        "sprint_speed": 73
      },
      "shooting_attributes": {
        "positioning": 38,
        "finishing": 40,
        "shot_power": 51,
        "long_shots": 40,
        "volleys": 44,
        "penalties": 48
      },
      "passing_attributes": {
        "vision": 59,
        "crossing": 57,
        "free_kick_accuracy": 34,
        "short_passing": 83,
        "long_passing": 73,
        "curve": 47
      },
      "dribbling_attributes": {
        "agility": 42,
        "balance": 53,
        "reactions": 90,
        "ball_control": 80,
        "dribbling": 68,
        "composure": 79
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 89,
        "standing_tackle": 97,
        "sliding_tackle": 98
      },
      "physicality_attributes": {
        "jumping": 85,
        "stamina": 84,
        "strength": 93,
        "aggression": 88
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93976,
      "resource_id": 246509,
      "name": "Stoichkov",
      "age": None,
      "resource_base_id": 246509,
      "fut_bin_id": 28703,
      "fut_wiz_id": 19820,
      "first_name": "Hristo",
      "last_name": "Stoichkov",
      "common_name": "Stoichkov",
      "height": 178,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 9,
      "club": 112658,
      "rarity": 84,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "ST",
      "skill_moves": 4,
      "weak_foot": 3,
      "foot": "Left",
      "attack_work_rate": "MED",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 85,
      "pace": 94,
      "shooting": 95,
      "passing": 89,
      "dribbling": 94,
      "defending": 52,
      "physicality": 88,
      "pace_attributes": {
        "acceleration": 95,
        "sprint_speed": 93
      },
      "shooting_attributes": {
        "positioning": 95,
        "finishing": 96,
        "shot_power": 95,
        "long_shots": 95,
        "volleys": 93,
        "penalties": 92
      },
      "passing_attributes": {
        "vision": 90,
        "crossing": 87,
        "free_kick_accuracy": 97,
        "short_passing": 89,
        "long_passing": 84,
        "curve": 95
      },
      "dribbling_attributes": {
        "agility": 93,
        "balance": 85,
        "reactions": 91,
        "ball_control": 95,
        "dribbling": 95,
        "composure": 92
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 85,
        "standing_tackle": 54,
        "sliding_tackle": 49
      },
      "physicality_attributes": {
        "jumping": 81,
        "stamina": 89,
        "strength": 85,
        "aggression": 94
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93977,
      "resource_id": 246527,
      "name": "Del Piero",
      "age": None,
      "resource_base_id": 246527,
      "fut_bin_id": 28702,
      "fut_wiz_id": 19822,
      "first_name": "Alessandro",
      "last_name": "Del Piero",
      "common_name": "Del Piero",
      "height": 174,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 27,
      "club": 112658,
      "rarity": 84,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CF",
      "skill_moves": 4,
      "weak_foot": 5,
      "foot": "Right",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 79,
      "pace": 85,
      "shooting": 94,
      "passing": 92,
      "dribbling": 94,
      "defending": 44,
      "physicality": 69,
      "pace_attributes": {
        "acceleration": 86,
        "sprint_speed": 84
      },
      "shooting_attributes": {
        "positioning": 96,
        "finishing": 97,
        "shot_power": 90,
        "long_shots": 93,
        "volleys": 88,
        "penalties": 99
      },
      "passing_attributes": {
        "vision": 96,
        "crossing": 91,
        "free_kick_accuracy": 99,
        "short_passing": 92,
        "long_passing": 83,
        "curve": 96
      },
      "dribbling_attributes": {
        "agility": 86,
        "balance": 67,
        "reactions": 91,
        "ball_control": 97,
        "dribbling": 97,
        "composure": 95
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 77,
        "standing_tackle": 43,
        "sliding_tackle": 37
      },
      "physicality_attributes": {
        "jumping": 59,
        "stamina": 84,
        "strength": 67,
        "aggression": 60
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93998,
      "resource_id": 100845817,
      "name": "Toni Kroos",
      "age": None,
      "resource_base_id": 182521,
      "fut_bin_id": 28751,
      "fut_wiz_id": 19844,
      "first_name": "Toni",
      "last_name": "Kroos",
      "common_name": "Kroos",
      "height": 183,
      "weight": None,
      "birth_date": None,
      "league": 53,
      "nation": 21,
      "club": 243,
      "rarity": 51,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CM",
      "skill_moves": 3,
      "weak_foot": 5,
      "foot": "Right",
      "attack_work_rate": "MED",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 83,
      "pace": 78,
      "shooting": 89,
      "passing": 95,
      "dribbling": 88,
      "defending": 76,
      "physicality": 76,
      "pace_attributes": {
        "acceleration": 82,
        "sprint_speed": 75
      },
      "shooting_attributes": {
        "positioning": 84,
        "finishing": 84,
        "shot_power": 98,
        "long_shots": 94,
        "volleys": 90,
        "penalties": 80
      },
      "passing_attributes": {
        "vision": 94,
        "crossing": 92,
        "free_kick_accuracy": 88,
        "short_passing": 97,
        "long_passing": 97,
        "curve": 90
      },
      "dribbling_attributes": {
        "agility": 80,
        "balance": 87,
        "reactions": 94,
        "ball_control": 94,
        "dribbling": 85,
        "composure": 93
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 61,
        "standing_tackle": 78,
        "sliding_tackle": 63
      },
      "physicality_attributes": {
        "jumping": 34,
        "stamina": 87,
        "strength": 80,
        "aggression": 64
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93243,
      "resource_id": 134426450,
      "name": "Sadio Mané",
      "age": None,
      "resource_base_id": 208722,
      "fut_bin_id": 27987,
      "fut_wiz_id": 18897,
      "first_name": "Sadio",
      "last_name": "Mané",
      "common_name": "Mané",
      "height": 175,
      "weight": None,
      "birth_date": None,
      "league": 13,
      "nation": 136,
      "club": 9,
      "rarity": 64,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "LW",
      "skill_moves": 4,
      "weak_foot": 4,
      "foot": "Right",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 82,
      "pace": 97,
      "shooting": 90,
      "passing": 85,
      "dribbling": 93,
      "defending": 47,
      "physicality": 81,
      "pace_attributes": {
        "acceleration": 98,
        "sprint_speed": 96
      },
      "shooting_attributes": {
        "positioning": 97,
        "finishing": 95,
        "shot_power": 89,
        "long_shots": 83,
        "volleys": 79,
        "penalties": 75
      },
      "passing_attributes": {
        "vision": 90,
        "crossing": 82,
        "free_kick_accuracy": 69,
        "short_passing": 90,
        "long_passing": 75,
        "curve": 81
      },
      "dribbling_attributes": {
        "agility": 96,
        "balance": 89,
        "reactions": 96,
        "ball_control": 92,
        "dribbling": 94,
        "composure": 87
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 89,
        "standing_tackle": 45,
        "sliding_tackle": 41
      },
      "physicality_attributes": {
        "jumping": 91,
        "stamina": 94,
        "strength": 75,
        "aggression": 79
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 92228,
      "resource_id": 10535,
      "name": "Hernández Creus",
      "age": None,
      "resource_base_id": 10535,
      "fut_bin_id": 26870,
      "fut_wiz_id": None,
      "first_name": None,
      "last_name": None,
      "common_name": "Xavi",
      "height": None,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 45,
      "club": 112658,
      "rarity": 12,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CM",
      "skill_moves": None,
      "weak_foot": None,
      "foot": None,
      "attack_work_rate": None,
      "defense_work_rate": None,
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 82,
      "pace": 81,
      "shooting": 80,
      "passing": 95,
      "dribbling": 93,
      "defending": 72,
      "physicality": 72,
      "pace_attributes": {
        "acceleration": None,
        "sprint_speed": None
      },
      "shooting_attributes": {
        "positioning": None,
        "finishing": None,
        "shot_power": None,
        "long_shots": None,
        "volleys": None,
        "penalties": None
      },
      "passing_attributes": {
        "vision": None,
        "crossing": None,
        "free_kick_accuracy": None,
        "short_passing": None,
        "long_passing": None,
        "curve": None
      },
      "dribbling_attributes": {
        "agility": None,
        "balance": None,
        "reactions": None,
        "ball_control": None,
        "dribbling": None,
        "composure": None
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": None,
        "standing_tackle": None,
        "sliding_tackle": None
      },
      "physicality_attributes": {
        "jumping": None,
        "stamina": None,
        "strength": None,
        "aggression": None
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93265,
      "resource_id": 50385698,
      "name": "Wayne Rooney",
      "age": None,
      "resource_base_id": 54050,
      "fut_bin_id": 28002,
      "fut_wiz_id": 18914,
      "first_name": "Wayne",
      "last_name": "Rooney",
      "common_name": "Rooney",
      "height": 176,
      "weight": None,
      "birth_date": None,
      "league": 14,
      "nation": 14,
      "club": 91,
      "rarity": 25,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "ST",
      "skill_moves": 4,
      "weak_foot": 4,
      "foot": "Right",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 87,
      "pace": 87,
      "shooting": 95,
      "passing": 88,
      "dribbling": 91,
      "defending": 71,
      "physicality": 90,
      "pace_attributes": {
        "acceleration": 89,
        "sprint_speed": 86
      },
      "shooting_attributes": {
        "positioning": 91,
        "finishing": 94,
        "shot_power": 99,
        "long_shots": 94,
        "volleys": 97,
        "penalties": 95
      },
      "passing_attributes": {
        "vision": 91,
        "crossing": 90,
        "free_kick_accuracy": 93,
        "short_passing": 84,
        "long_passing": 90,
        "curve": 87
      },
      "dribbling_attributes": {
        "agility": 86,
        "balance": 80,
        "reactions": 95,
        "ball_control": 94,
        "dribbling": 91,
        "composure": 99
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 95,
        "standing_tackle": 70,
        "sliding_tackle": 51
      },
      "physicality_attributes": {
        "jumping": 82,
        "stamina": 90,
        "strength": 90,
        "aggression": 91
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 92264,
      "resource_id": 167198,
      "name": "Éric Cantona",
      "age": None,
      "resource_base_id": 167198,
      "fut_bin_id": 985,
      "fut_wiz_id": None,
      "first_name": None,
      "last_name": None,
      "common_name": "Cantona",
      "height": None,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 18,
      "club": 112658,
      "rarity": 12,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CF",
      "skill_moves": None,
      "weak_foot": None,
      "foot": None,
      "attack_work_rate": None,
      "defense_work_rate": None,
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 85,
      "pace": 89,
      "shooting": 93,
      "passing": 90,
      "dribbling": 93,
      "defending": 53,
      "physicality": 92,
      "pace_attributes": {
        "acceleration": None,
        "sprint_speed": None
      },
      "shooting_attributes": {
        "positioning": None,
        "finishing": None,
        "shot_power": None,
        "long_shots": None,
        "volleys": None,
        "penalties": None
      },
      "passing_attributes": {
        "vision": None,
        "crossing": None,
        "free_kick_accuracy": None,
        "short_passing": None,
        "long_passing": None,
        "curve": None
      },
      "dribbling_attributes": {
        "agility": None,
        "balance": None,
        "reactions": None,
        "ball_control": None,
        "dribbling": None,
        "composure": None
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": None,
        "standing_tackle": None,
        "sliding_tackle": None
      },
      "physicality_attributes": {
        "jumping": None,
        "stamina": None,
        "strength": None,
        "aggression": None
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 93039,
      "resource_id": 84120476,
      "name": "Alphonso Davies",
      "age": None,
      "resource_base_id": 234396,
      "fut_bin_id": 27949,
      "fut_wiz_id": 18847,
      "first_name": "Alphonso",
      "last_name": "Davies",
      "common_name": "Davies",
      "height": 181,
      "weight": None,
      "birth_date": None,
      "league": 19,
      "nation": 70,
      "club": 21,
      "rarity": 5,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "LB",
      "skill_moves": 4,
      "weak_foot": 4,
      "foot": "Left",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 91,
      "pace": 99,
      "shooting": 83,
      "passing": 89,
      "dribbling": 96,
      "defending": 91,
      "physicality": 90,
      "pace_attributes": {
        "acceleration": 99,
        "sprint_speed": 99
      },
      "shooting_attributes": {
        "positioning": 93,
        "finishing": 83,
        "shot_power": 88,
        "long_shots": 78,
        "volleys": 73,
        "penalties": 74
      },
      "passing_attributes": {
        "vision": 88,
        "crossing": 94,
        "free_kick_accuracy": 57,
        "short_passing": 99,
        "long_passing": 75,
        "curve": 86
      },
      "dribbling_attributes": {
        "agility": 99,
        "balance": 96,
        "reactions": 92,
        "ball_control": 92,
        "dribbling": 99,
        "composure": 87
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 77,
        "standing_tackle": 92,
        "sliding_tackle": 95
      },
      "physicality_attributes": {
        "jumping": 91,
        "stamina": 94,
        "strength": 88,
        "aggression": 91
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 92018,
      "resource_id": 84074625,
      "name": "Robert Lewandowski",
      "age": None,
      "resource_base_id": 188545,
      "fut_bin_id": 26634,
      "fut_wiz_id": 17853,
      "first_name": "Robert",
      "last_name": "Lewandowski",
      "common_name": "Lewandowski",
      "height": 184,
      "weight": None,
      "birth_date": None,
      "league": 19,
      "nation": 37,
      "club": 21,
      "rarity": 42,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "ST",
      "skill_moves": 4,
      "weak_foot": 4,
      "foot": "Right",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 79,
      "pace": 80,
      "shooting": 93,
      "passing": 82,
      "dribbling": 89,
      "defending": 45,
      "physicality": 85,
      "pace_attributes": {
        "acceleration": 79,
        "sprint_speed": 80
      },
      "shooting_attributes": {
        "positioning": 96,
        "finishing": 96,
        "shot_power": 91,
        "long_shots": 87,
        "volleys": 91,
        "penalties": 90
      },
      "passing_attributes": {
        "vision": 83,
        "crossing": 75,
        "free_kick_accuracy": 89,
        "short_passing": 88,
        "long_passing": 74,
        "curve": 83
      },
      "dribbling_attributes": {
        "agility": 80,
        "balance": 85,
        "reactions": 96,
        "ball_control": 91,
        "dribbling": 88,
        "composure": 91
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 89,
        "standing_tackle": 44,
        "sliding_tackle": 20
      },
      "physicality_attributes": {
        "jumping": 87,
        "stamina": 79,
        "strength": 89,
        "aggression": 84
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 90778,
      "resource_id": 996,
      "name": "Éric Cantona",
      "age": None,
      "resource_base_id": 996,
      "fut_bin_id": 985,
      "fut_wiz_id": 734,
      "first_name": "Eric",
      "last_name": "Cantona",
      "common_name": "Cantona",
      "height": 188,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 18,
      "club": 112658,
      "rarity": 12,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CF",
      "skill_moves": 0,
      "weak_foot": 0,
      "foot": "",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 85,
      "pace": 89,
      "shooting": 93,
      "passing": 90,
      "dribbling": 93,
      "defending": 53,
      "physicality": 92,
      "pace_attributes": {
        "acceleration": 0,
        "sprint_speed": 0
      },
      "shooting_attributes": {
        "positioning": 0,
        "finishing": 0,
        "shot_power": 0,
        "long_shots": 0,
        "volleys": 0,
        "penalties": 0
      },
      "passing_attributes": {
        "vision": 0,
        "crossing": 0,
        "free_kick_accuracy": 0,
        "short_passing": 0,
        "long_passing": 0,
        "curve": 0
      },
      "dribbling_attributes": {
        "agility": 0,
        "balance": 0,
        "reactions": 0,
        "ball_control": 0,
        "dribbling": 0,
        "composure": 0
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 0,
        "standing_tackle": 0,
        "sliding_tackle": 0
      },
      "physicality_attributes": {
        "jumping": 0,
        "stamina": 0,
        "strength": 0,
        "aggression": 0
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 90779,
      "resource_id": 166906,
      "name": "Franco Baresi",
      "age": None,
      "resource_base_id": 166906,
      "fut_bin_id": 63,
      "fut_wiz_id": 90,
      "first_name": "Franco",
      "last_name": "Baresi",
      "common_name": "Baresi",
      "height": 176,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 27,
      "club": 112658,
      "rarity": 12,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CB",
      "skill_moves": 0,
      "weak_foot": 0,
      "foot": "",
      "attack_work_rate": "MED",
      "defense_work_rate": "HIGH",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 74,
      "pace": 70,
      "shooting": 49,
      "passing": 76,
      "dribbling": 72,
      "defending": 95,
      "physicality": 82,
      "pace_attributes": {
        "acceleration": 0,
        "sprint_speed": 0
      },
      "shooting_attributes": {
        "positioning": 0,
        "finishing": 0,
        "shot_power": 0,
        "long_shots": 0,
        "volleys": 0,
        "penalties": 0
      },
      "passing_attributes": {
        "vision": 0,
        "crossing": 0,
        "free_kick_accuracy": 0,
        "short_passing": 0,
        "long_passing": 0,
        "curve": 0
      },
      "dribbling_attributes": {
        "agility": 0,
        "balance": 0,
        "reactions": 0,
        "ball_control": 0,
        "dribbling": 0,
        "composure": 0
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 0,
        "standing_tackle": 0,
        "sliding_tackle": 0
      },
      "physicality_attributes": {
        "jumping": 0,
        "stamina": 0,
        "strength": 0,
        "aggression": 0
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 90780,
      "resource_id": 238435,
      "name": "Lothar Matthäus",
      "age": None,
      "resource_base_id": 238435,
      "fut_bin_id": 121,
      "fut_wiz_id": 167,
      "first_name": "Lothar",
      "last_name": "Matthaus",
      "common_name": "Matthäus",
      "height": 174,
      "weight": None,
      "birth_date": None,
      "league": 2118,
      "nation": 21,
      "club": 112658,
      "rarity": 12,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "CM",
      "skill_moves": 0,
      "weak_foot": 0,
      "foot": "",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "HIGH",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 87,
      "pace": 89,
      "shooting": 89,
      "passing": 90,
      "dribbling": 82,
      "defending": 90,
      "physicality": 85,
      "pace_attributes": {
        "acceleration": 0,
        "sprint_speed": 0
      },
      "shooting_attributes": {
        "positioning": 0,
        "finishing": 0,
        "shot_power": 0,
        "long_shots": 0,
        "volleys": 0,
        "penalties": 0
      },
      "passing_attributes": {
        "vision": 0,
        "crossing": 0,
        "free_kick_accuracy": 0,
        "short_passing": 0,
        "long_passing": 0,
        "curve": 0
      },
      "dribbling_attributes": {
        "agility": 0,
        "balance": 0,
        "reactions": 0,
        "ball_control": 0,
        "dribbling": 0,
        "composure": 0
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 0,
        "standing_tackle": 0,
        "sliding_tackle": 0
      },
      "physicality_attributes": {
        "jumping": 0,
        "stamina": 0,
        "strength": 0,
        "aggression": 0
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 92076,
      "resource_id": 67129665,
      "name": "Cristiano Ronaldo",
      "age": None,
      "resource_base_id": 20801,
      "fut_bin_id": 26692,
      "fut_wiz_id": None,
      "first_name": None,
      "last_name": None,
      "common_name": "Ronaldo",
      "height": None,
      "weight": None,
      "birth_date": None,
      "league": 31,
      "nation": 38,
      "club": 114153,
      "rarity": 3,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "ST",
      "skill_moves": None,
      "weak_foot": None,
      "foot": None,
      "attack_work_rate": None,
      "defense_work_rate": None,
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 78,
      "pace": 90,
      "shooting": 94,
      "passing": 83,
      "dribbling": 91,
      "defending": 36,
      "physicality": 78,
      "pace_attributes": {
        "acceleration": None,
        "sprint_speed": None
      },
      "shooting_attributes": {
        "positioning": None,
        "finishing": None,
        "shot_power": None,
        "long_shots": None,
        "volleys": None,
        "penalties": None
      },
      "passing_attributes": {
        "vision": None,
        "crossing": None,
        "free_kick_accuracy": None,
        "short_passing": None,
        "long_passing": None,
        "curve": None
      },
      "dribbling_attributes": {
        "agility": None,
        "balance": None,
        "reactions": None,
        "ball_control": None,
        "dribbling": None,
        "composure": None
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": None,
        "standing_tackle": None,
        "sliding_tackle": None
      },
      "physicality_attributes": {
        "jumping": None,
        "stamina": None,
        "strength": None,
        "aggression": None
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 91622,
      "resource_id": 50489671,
      "name": "Lionel Messi",
      "age": None,
      "resource_base_id": 158023,
      "fut_bin_id": 25795,
      "fut_wiz_id": 16943,
      "first_name": "Lionel",
      "last_name": "Messi",
      "common_name": "Messi",
      "height": 170,
      "weight": None,
      "birth_date": None,
      "league": 53,
      "nation": 52,
      "club": 241,
      "rarity": 48,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "RW",
      "skill_moves": 4,
      "weak_foot": 4,
      "foot": "Left",
      "attack_work_rate": "MED",
      "defense_work_rate": "LOW",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 77,
      "pace": 85,
      "shooting": 92,
      "passing": 91,
      "dribbling": 95,
      "defending": 38,
      "physicality": 65,
      "pace_attributes": {
        "acceleration": 91,
        "sprint_speed": 80
      },
      "shooting_attributes": {
        "positioning": 93,
        "finishing": 95,
        "shot_power": 86,
        "long_shots": 94,
        "volleys": 88,
        "penalties": 75
      },
      "passing_attributes": {
        "vision": 95,
        "crossing": 85,
        "free_kick_accuracy": 94,
        "short_passing": 91,
        "long_passing": 91,
        "curve": 93
      },
      "dribbling_attributes": {
        "agility": 91,
        "balance": 95,
        "reactions": 94,
        "ball_control": 96,
        "dribbling": 96,
        "composure": 96
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 70,
        "standing_tackle": 35,
        "sliding_tackle": 24
      },
      "physicality_attributes": {
        "jumping": 68,
        "stamina": 72,
        "strength": 69,
        "aggression": 44
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    },
    {
      "id": 92402,
      "resource_id": 100851841,
      "name": "Robert Lewandowski",
      "age": None,
      "resource_base_id": 188545,
      "fut_bin_id": 27095,
      "fut_wiz_id": 18173,
      "first_name": "Robert",
      "last_name": "Lewandowski",
      "common_name": "Lewandowski",
      "height": 184,
      "weight": None,
      "birth_date": None,
      "league": 19,
      "nation": 37,
      "club": 21,
      "rarity": 3,
      "traits": [],
      "specialities": [],
      "tradeable": True,
      "position": "ST",
      "skill_moves": 4,
      "weak_foot": 4,
      "foot": "Right",
      "attack_work_rate": "HIGH",
      "defense_work_rate": "MED",
      "total_stats": None,
      "total_stats_in_game": None,
      "rating": 93,
      "rating_average": 79,
      "pace": 81,
      "shooting": 93,
      "passing": 82,
      "dribbling": 88,
      "defending": 45,
      "physicality": 85,
      "pace_attributes": {
        "acceleration": 80,
        "sprint_speed": 81
      },
      "shooting_attributes": {
        "positioning": 96,
        "finishing": 96,
        "shot_power": 91,
        "long_shots": 87,
        "volleys": 91,
        "penalties": 90
      },
      "passing_attributes": {
        "vision": 83,
        "crossing": 75,
        "free_kick_accuracy": 89,
        "short_passing": 88,
        "long_passing": 74,
        "curve": 83
      },
      "dribbling_attributes": {
        "agility": 79,
        "balance": 84,
        "reactions": 95,
        "ball_control": 90,
        "dribbling": 87,
        "composure": 90
      },
      "defending_attributes": {
        "interceptions": None,
        "heading_accuracy": 89,
        "standing_tackle": 44,
        "sliding_tackle": 20
      },
      "physicality_attributes": {
        "jumping": 87,
        "stamina": 79,
        "strength": 89,
        "aggression": 84
      },
      "goalkeeper_attributes": {
        "diving": None,
        "handling": None,
        "kicking": None,
        "positioning": None,
        "reflexes": None
      }
    }
  ]
}

for value in jogador["items"]:
  print(value["first_name"])
  print(value["common_name"])
  print(value["last_name"])
  print(value["foot"])
  print(value["name"])
  print(value["shooting"])
  print(value["passing"])
  print(value["shooting_attributes"]["shot_power"])
  print()
